"""Assemble report/report.md from report/report_template.md + results/, then convert with pandoc.

Every number in the finished report comes from results/*.json or results/tables/*.md (written by
make_report_assets.py). Nothing is typed in by hand: a run that has not been done shows up as
"not run" instead of a value.

Template syntax
  {{key}}                       a value computed in values()
  <!--TABLE:name-->             contents of results/tables/name.md
  <!--FIG:file.png|caption-->   the figure results/figures/file.png (or a "not generated" note)
  <!--AUTO:name-->              a paragraph generated by auto_<name>()

    python src/build_report.py            # report.md + report.docx (+ report.pdf if a LaTeX engine exists)
    python src/build_report.py --no-docx  # markdown only
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import re
import shutil
import subprocess

import numpy as np

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RES = os.path.join(ROOT, "results")
REP = os.path.join(ROOT, "report")
NA = "*not run*"

PAPER = {"sst2": {"full": 91.3, "noaux": 92.0, "nopre": 84.0, "lstm": 90.5},
         "mrpc": {"full": 82.3, "noaux": 84.9, "nopre": 79.4, "lstm": 83.2}}


# ----------------------------------------------------------------------------- loading helpers
def load(pattern):
    out = []
    for p in sorted(glob.glob(os.path.join(RES, pattern))):
        with open(p, encoding="utf-8") as f:
            r = json.load(f)
        if not r.get("quick"):
            out.append(r)
    return out


def jload(path):
    p = os.path.join(RES, path)
    if os.path.exists(p):
        with open(p, encoding="utf-8") as f:
            return json.load(f)
    return None


def vals(exp, task, key):
    return [100 * r["metrics"][key] for r in load(f"{exp}_{task}_seed*.json")]


def mean(v):
    return float(np.mean(v)) if v else None


def ms(v):
    if not v:
        return NA
    return f"{np.mean(v):.2f}" if len(v) == 1 else f"{np.mean(v):.2f} ± {np.std(v, ddof=1):.2f}"


def f2(x):
    return NA if x is None else f"{x:.2f}"


def sgn(x):
    return f"{x:+.2f}"


# ----------------------------------------------------------------------------- scalar values
def values():
    V = {}
    wm = jload("weight_match.json")
    V["wm_maxdiff"] = f"{wm['max_abs_diff']:.2e}" if wm else NA
    V["wm_status"] = ("passed" if wm and wm["passed"] else "not yet run")
    V["n_params_hf"] = f"{wm['n_parameters_hf']:,}" if wm else NA
    any_run = (load("E1_*.json") + load("E2_*.json") + load("E3_*.json"))
    c = any_run[0]["compute"] if any_run else None
    V["n_params_clf"] = f"{c['n_parameters']:,}" if c else NA
    V["gpu"] = c["gpu"] if c else NA
    V["torch_version"] = c["torch"] if c else NA
    V["tf_version"] = (c.get("transformers") or NA) if c else NA
    V["platform"] = c["platform"] if c else NA
    h = any_run[0]["hyperparams"] if any_run else None
    V["micro_batch"] = str(h["micro_batch"]) if h else NA
    V["grad_accum"] = str(h["grad_accum"]) if h else NA
    oom = sum(len(r.get("oom_events", [])) for r in any_run)
    V["oom_total"] = str(oom)
    V["tok_mode"] = any_run[0]["data"]["tokenizer_mode"] if any_run else NA
    for t in ("sst2", "mrpc"):
        s = jload(f"length_stats_{t}.json")
        V[f"{t}_maxlen"] = str(s["chosen_max_len"]) if s else NA
        V[f"{t}_len_train_mean"] = f"{s['train']['mean']:.1f}" if s else NA
        V[f"{t}_len_val_mean"] = f"{s['validation']['mean']:.1f}" if s else NA
        V[f"{t}_len_train_max"] = str(s["train"]["max"]) if s else NA
        V[f"{t}_n_train"] = str(s["train"]["n"]) if s else NA
        V[f"{t}_n_val"] = str(s["validation"]["n"]) if s else NA
    V["e1_sst2_acc"] = ms(vals("E1", "sst2", "accuracy"))
    V["e1_mrpc_f1"] = ms(vals("E1", "mrpc", "f1_pos"))
    V["e1_mrpc_acc"] = ms(vals("E1", "mrpc", "accuracy"))
    V["mrpc_seeds"] = ", ".join(str(r["hyperparams"]["seed"]) for r in load("E1_mrpc_seed*.json")) or NA
    gpu_min = sum(r["compute"]["train_time_s"] for r in any_run + load("E6_*.json")) / 60
    V["gpu_hours"] = f"{gpu_min / 60:.1f}" if any_run else NA
    peaks = [r["compute"]["peak_vram_mib"] for r in any_run + load("E6_*.json") if r["compute"].get("peak_vram_mib")]
    V["peak_vram_max"] = f"{max(peaks):.0f}" if peaks else NA
    return V


# ----------------------------------------------------------------------------- generated paragraphs
def auto_abstract_results():
    e1s, e1m = mean(vals("E1", "sst2", "accuracy")), mean(vals("E1", "mrpc", "f1_pos"))
    e4s = load("E4_tfidf_lr_sst2.json")
    parts = []
    if e1s is not None:
        parts.append(f"fine-tuning the released GPT-1 weights reaches {e1s:.2f}% accuracy on the SST-2 "
                     f"validation set (paper: {PAPER['sst2']['full']}% on the GLUE test set)")
    if e1m is not None:
        parts.append(f"{e1m:.2f} F1 on MRPC validation (paper: {PAPER['mrpc']['full']} test)")
    if e4s:
        parts.append(f"a TF-IDF + logistic-regression baseline reaches {100 * e4s[0]['metrics']['accuracy']:.2f}% on SST-2")
    e3 = mean(vals("E3", "sst2", "accuracy"))
    if e3 is not None:
        parts.append(f"the identical Transformer trained from random initialisation reaches {e3:.2f}%")
    if not parts:
        return "*Results will appear here once the experiments have been run (see README).*"
    return "On our hardware, " + "; ".join(parts) + "."


def auto_findings_sst2():
    e = {x: mean(vals(x, "sst2", "accuracy")) for x in ("E1", "E2", "E3")}
    e4 = load("E4_tfidf_lr_sst2.json")
    e5 = load("E5_zeroshot_sst2.json")
    out = []
    if e["E1"] is not None:
        out.append(f"- **Main result (E1).** GPT-1 fine-tuned with the auxiliary LM objective reaches "
                   f"**{e['E1']:.2f}%** validation accuracy, {sgn(e['E1'] - PAPER['sst2']['full'])} points "
                   f"relative to the paper's {PAPER['sst2']['full']}% (test set, so not directly comparable).")
    if e["E1"] is not None and e["E2"] is not None:
        out.append(f"- **Auxiliary LM loss (E1 vs E2).** {aux_sentence('sst2', 'accuracy')}")
    if e["E1"] is not None and e["E3"] is not None:
        out.append(f"- **Pre-training (E1 vs E3).** Without generative pre-training the same 12-layer "
                   f"Transformer reaches {e['E3']:.2f}%, a drop of {e['E1'] - e['E3']:.2f} points "
                   f"(paper: {PAPER['sst2']['full']} → {PAPER['sst2']['nopre']}, a drop of "
                   f"{PAPER['sst2']['full'] - PAPER['sst2']['nopre']:.1f})."
                   + (" This is the largest effect among our ablations, as in the paper."
                      if e["E2"] is None or e["E1"] - e["E3"] > abs(e["E1"] - e["E2"]) else ""))
    if e4 and e["E1"] is not None:
        b = 100 * e4[0]["metrics"]["accuracy"]
        out.append(f"- **Classical baseline (E4).** TF-IDF + logistic regression reaches {b:.2f}%; GPT-1 is "
                   f"{e['E1'] - b:.2f} points better." +
                   (f" The randomly initialised Transformer (E3) is {'below' if e['E3'] < b else 'above'} "
                    f"this linear baseline ({e['E3']:.2f}% vs {b:.2f}%)"
                    + (": without pre-training, 116 M parameters trained on the labelled phrases alone do not beat "
                       "a bag-of-n-grams model." if e["E3"] <= b + NOISE["sst2"] else ".")
                    if e["E3"] is not None else ""))
    if e5:
        z = e5[0]
        out.append(f"- **Zero-shot (E5).** With the paper's heuristic and no training at all, the language model "
                   f"alone scores {100 * z['metrics']['accuracy']:.2f}% (majority-class guess: "
                   f"{100 * z['chance_majority_acc']:.2f}%); it predicts *positive* for "
                   f"{100 * z['frac_pred_positive']:.1f}% of sentences (true rate {100 * z['frac_true_positive']:.1f}%).")
    return "\n".join(out) or "*SST-2 runs not done yet.*"


def auto_findings_mrpc():
    f = {x: vals(x, "mrpc", "f1_pos") for x in ("E1", "E2", "E3")}
    a = {x: vals(x, "mrpc", "accuracy") for x in ("E1", "E2", "E3")}
    e4 = load("E4_tfidf_lr_mrpc.json")
    out = []
    if f["E1"]:
        out.append(f"- **Main result (E1).** F1 (positive class) = **{ms(f['E1'])}**, accuracy {ms(a['E1'])} "
                   f"over {len(f['E1'])} seed(s); paper: {PAPER['mrpc']['full']} F1 on the GLUE test set.")
    if f["E1"] and f["E2"]:
        d = mean(f["E2"]) - mean(f["E1"])
        sd = max(np.std(f["E1"], ddof=1) if len(f["E1"]) > 1 else 0, np.std(f["E2"], ddof=1) if len(f["E2"]) > 1 else 0)
        noise = (f" The difference is {'smaller' if abs(d) < sd else 'larger'} than the seed-to-seed standard "
                 f"deviation ({sd:.2f}), so it is {'not' if abs(d) < sd else 'plausibly'} a real effect."
                 if sd > 0 else "")
        out.append(f"- **Auxiliary LM loss (E1 vs E2).** λ = 0 changes mean F1 by {sgn(d)} points.{noise} "
                   f"The paper also found MRPC better *without* the auxiliary loss ({PAPER['mrpc']['noaux']} vs "
                   f"{PAPER['mrpc']['full']}).")
    if f["E1"] and f["E3"]:
        out.append(f"- **Pre-training (E1 vs E3).** Random initialisation gives F1 {ms(f['E3'])} and accuracy "
                   f"{ms(a['E3'])}. F1 on MRPC is a misleading metric for a weak model: about two thirds of MRPC "
                   f"pairs are paraphrases, so predicting \"paraphrase\" for everything already gives a high F1; "
                   f"accuracy and macro-F1 in the table show the gap more honestly.")
    if e4 and f["E1"]:
        out.append(f"- **Classical baseline (E4).** TF-IDF + LR on symmetric pair features: F1 "
                   f"{100 * e4[0]['metrics']['f1_pos']:.2f}, accuracy {100 * e4[0]['metrics']['accuracy']:.2f}%.")
    return "\n".join(out) or "*MRPC runs not done yet.*"


def auto_layers():
    pts = [(r["setting"]["transfer_layers"], r) for r in load("E6_mrpc_k*_seed42.json")]
    pts += [(12, r) for r in load("E1_mrpc_seed42.json")]
    if len(pts) < 2:
        return "*Layer-transfer runs not done yet.*"
    pts.sort(key=lambda t: t[0])
    acc = [100 * r["metrics"]["accuracy"] for _, r in pts]
    ks = [k for k, _ in pts]
    mono = all(b >= a - 0.5 for a, b in zip(acc, acc[1:]))
    e3 = load("E3_mrpc_seed42.json")
    s = (f"Accuracy goes from {acc[0]:.2f}% with k = {ks[0]} (only embeddings transferred) to {acc[-1]:.2f}% with "
         f"k = {ks[-1]}, a gain of {acc[-1] - acc[0]:.2f} points. ")
    s += ("The curve rises (almost) monotonically, i.e. every additional block of pre-trained layers helps, "
          "which is the same qualitative trend the paper shows for MultiNLI and RACE (Fig. 2, left). "
          if mono else
          "The curve is not monotonic: with a single seed on a 408-example validation set, differences of one or "
          "two points are within noise (one example = 0.25 points), so only the overall trend should be read. ")
    if e3:
        s += (f"For reference, training everything from scratch (E3, no pre-trained embeddings either) gives "
              f"{100 * e3[0]['metrics']['accuracy']:.2f}%.")
    return s


def auto_zeroshot():
    z = load("E5_zeroshot_sst2.json")
    if not z:
        return "*Zero-shot run not done yet.*"
    z = z[0]
    d = z["diagnostic_median_threshold"]["metrics"]["accuracy"] * 100
    return (f"The paper's rule gives {100 * z['metrics']['accuracy']:.2f}% accuracy with no labelled data. "
            f"The model predicts *positive* for {100 * z['frac_pred_positive']:.1f}% of sentences although "
            f"{100 * z['frac_true_positive']:.1f}% are positive, i.e. part of the error is a constant preference for "
            f"one of the two label words rather than a lack of sentiment knowledge. Moving the threshold to the median "
            f"log-odds (a diagnostic only, not the paper's method) gives {d:.2f}%, which shows how much sentiment "
            f"information the purely generative model already carries before any fine-tuning.")


def auto_misclassified():
    cue = jload("tables/error_cues_sst2.json")
    if not cue:
        return "*Error analysis available after E1 has been run.*"
    r = cue["cue_rates"]
    lines = [f"Among the {cue['n_errors']} errors of E1 (seed 42), the automatic cue rates compared with the "
             f"{cue['n_correct']} correctly classified sentences are:", ""]
    lines += ["| Cue | % of errors | % of correct predictions |", "|---|---|---|"]
    for k, v in r.items():
        lines.append(f"| {k} | {100 * v['errors']:.1f} | {100 * v['correct']:.1f} |")
    over = [k for k, v in r.items() if v["errors"] > 1.2 * v["correct"] and v["errors"] > 0.05]
    lines += ["", ("Cues over-represented among errors: **" + ", ".join(over) + "**." if over else
                   "No cue is strongly over-represented among errors.")]
    return "\n".join(lines)


def auto_attention():
    a = jload("tables/attention_sentence.json")
    if not a:
        return "*Attention map available after E1 has been run (`make_report_assets.py --attention`).*"
    toks, row = a["tokens"], np.array(a["e_row_last_layer"])
    order = [i for i in np.argsort(-row) if 0 < i < len(toks) - 1][:4]
    top = ", ".join(f"“{toks[i]}” ({row[i]:.2f})" for i in order)
    return (f"For the sentence *“{a['sentence']}”*, the ⟨e⟩ token in the last layer places its largest attention "
            f"weights (averaged over heads, excluding ⟨s⟩ and ⟨e⟩) on {top}. The weight on ⟨s⟩ is "
            f"{row[0]:.2f}; heavy attention to the first token is a well-known \"attention sink\" pattern and is not "
            f"by itself evidence that the token matters. Attention weights are a diagnostic, not an explanation.")


def auto_curves():
    out = []
    for task in ("sst2", "mrpc"):
        for r in load(f"E1_{task}_seed42.json"):
            c = r["curves"]
            if not c["val_acc"]:
                continue
            best = int(np.argmax(c["val_acc"]))
            gap = c["train_acc"][-1] - c["val_acc"][-1]
            vmin = int(np.argmin(c["val_loss"]))
            out.append(f"- **{task.upper()} (E1, seed 42):** best validation accuracy {100 * c['val_acc'][best]:.2f}% at "
                       f"epoch {c['epoch'][best]:.2f}, final {100 * c['val_acc'][-1]:.2f}%; validation loss is lowest at "
                       f"epoch {c['epoch'][vmin]:.2f} and ends at {c['val_loss'][-1]:.3f} "
                       f"({'rising after its minimum, a mild sign of over-confidence' if vmin < len(c['val_loss']) - 1 else 'still at its minimum'}). "
                       f"Final train–validation accuracy gap: {100 * gap:.1f} points. We report the final-epoch model "
                       f"(no checkpoint selection on the validation set).")
    return "\n".join(out) or "*Curves available after E1 has been run.*"


NOISE = {"sst2": 0.5, "mrpc": 1.0}   # |difference| (points) below which one seed cannot separate two settings


def aux_sentence(task, key):
    e1, e2 = vals("E1", task, key), vals("E2", task, key)
    if not (e1 and e2):
        return "*E1 and E2 are both needed for this comparison.*"
    d = mean(e2) - mean(e1)
    sd = max([np.std(v, ddof=1) for v in (e1, e2) if len(v) > 1] or [0.0])
    thr = max(NOISE[task], sd)
    pd = PAPER[task]["noaux"] - PAPER[task]["full"]
    metric = "accuracy" if key == "accuracy" else "F1"
    s = (f"Removing the auxiliary objective (λ = 0) changes {metric} by {sgn(d)} points "
         f"({f2(mean(e1))} → {f2(mean(e2))}; paper, Table 5: {PAPER[task]['full']} → {PAPER[task]['noaux']}, "
         f"{sgn(pd)}). ")
    if abs(d) < thr:
        s += (f"This is within what seed-to-seed variation alone produces (≈{thr:.1f} points), so on {task.upper()} "
              f"we see no measurable benefit from the auxiliary loss, consistent with the paper's remark that "
              f"smaller datasets do not benefit from it.")
    elif d > 0:
        s += ("As in the paper, the model is better without the auxiliary loss on this dataset.")
    else:
        s += ("Unlike the paper's ablation on this dataset, the auxiliary loss helped in our runs.")
    return s


def auto_aux_discussion():
    return " ".join(f"**{t.upper()}:** {aux_sentence(t, k)}" for t, k in (("sst2", "accuracy"), ("mrpc", "f1_pos")))


def ablation_drops(task, key):
    e1 = mean(vals("E1", task, key))
    if e1 is None:
        return None
    d = {}
    for x, lab in (("E2", "no auxiliary LM"), ("E3", "no pre-training")):
        v = mean(vals(x, task, key))
        if v is not None:
            d[lab] = e1 - v
    return d


def auto_pretrain_discussion():
    out = []
    for t, k, name in (("sst2", "accuracy", "accuracy"), ("mrpc", "accuracy", "accuracy")):
        d = ablation_drops(t, k)
        if not d or "no pre-training" not in d:
            continue
        largest = max(d, key=lambda z: d[z])
        out.append(f"On {t.upper()}, removing pre-training costs {d['no pre-training']:.2f} points of {name}"
                   + (", the largest drop of our ablations, as in the paper." if largest == "no pre-training"
                      else f", less than removing the {largest} ({d[largest]:.2f}), unlike the paper."))
    pts = sorted([(r["setting"]["transfer_layers"], 100 * r["metrics"]["accuracy"]) for r in load("E6_mrpc_k*_seed42.json")]
                 + [(12, 100 * r["metrics"]["accuracy"]) for r in load("E1_mrpc_seed42.json")])
    if len(pts) >= 3:
        gain = pts[-1][1] - pts[0][1]
        out.append(f"The layer-transfer runs (E6) refine this: going from embeddings only (k = {pts[0][0]}) to all "
                   f"{pts[-1][0]} blocks changes MRPC accuracy by {sgn(gain)} points"
                   + (", so the useful knowledge is spread over the depth of the network and not only in the "
                      "embeddings, as in the paper's Fig. 2 (left)." if gain > NOISE["mrpc"] else
                      ", which is too small to separate from noise on 408 validation pairs with one seed."))
    return " ".join(out) or "*Our corresponding measurements appear here once E1, E3 and E6 have been run.*"


def auto_baseline_discussion():
    out = []
    for t, k in (("sst2", "accuracy"), ("mrpc", "accuracy")):
        b, e1, e3 = load(f"E4_tfidf_lr_{t}.json"), mean(vals("E1", t, k)), mean(vals("E3", t, k))
        if b and e1 is not None:
            bv = 100 * b[0]["metrics"][k]
            s = f"On {t.upper()} the baseline reaches {bv:.2f}% accuracy against {e1:.2f}% for GPT-1 ({sgn(e1 - bv)})"
            if e3 is not None:
                s += f", while the randomly initialised Transformer reaches {e3:.2f}% ({sgn(e3 - bv)} relative to the baseline)"
            out.append(s + ".")
    return " ".join(out) or "*Measured comparison appears once E1 and E4 have been run.*"


def auto_zeroshot_discussion():
    z = load("E5_zeroshot_sst2.json")
    if not z:
        return "*Our zero-shot measurement appears here once E5 has been run.*"
    z = z[0]
    acc, maj = 100 * z["metrics"]["accuracy"], 100 * z["chance_majority_acc"]
    diag = 100 * z["diagnostic_median_threshold"]["metrics"]["accuracy"]
    e1 = mean(vals("E1", "sst2", "accuracy"))
    s = (f"With the paper's exact heuristic our model scores {acc:.2f}% against a majority-class rate of {maj:.2f}%"
         + (", i.e. above chance without ever seeing a label" if acc > maj + 2 else
            ", i.e. not clearly above chance with the fixed decision rule"))
    s += (f"; with the bias-corrected threshold it reaches {diag:.2f}%, "
          + ("which shows that the log-odds do carry sentiment information." if diag > maj + 5 else
             "so the sentiment signal in the raw LM is weak.") )
    if e1 is not None:
        s += f" Fine-tuning (E1, {e1:.2f}%) remains far better."
    return s


def auto_conclusion():
    rows = []
    d_s = ablation_drops("sst2", "accuracy") or {}
    d_m = ablation_drops("mrpc", "accuracy") or {}
    def verdict(ok, msg_ok, msg_no, have):
        if not have:
            return "not tested (runs missing)"
        return msg_ok if ok else msg_no
    have = "no pre-training" in d_s or "no pre-training" in d_m
    ok = all(v.get("no pre-training", -1) >= max(v.values()) for v in (d_s, d_m) if "no pre-training" in v)
    rows.append(("Pre-training is the most important ingredient", verdict(ok, "reproduced", "not reproduced", have)))
    pts = sorted([(r["setting"]["transfer_layers"], 100 * r["metrics"]["accuracy"]) for r in load("E6_mrpc_k*_seed42.json")]
                 + [(12, 100 * r["metrics"]["accuracy"]) for r in load("E1_mrpc_seed42.json")])
    rows.append(("Transferring more pre-trained layers helps",
                 verdict(len(pts) >= 3 and pts[-1][1] - pts[0][1] > NOISE["mrpc"], "reproduced (overall trend)",
                         "not clearly reproduced", len(pts) >= 3)))
    aux = []
    for t, k in (("sst2", "accuracy"), ("mrpc", "f1_pos")):
        e1, e2 = vals("E1", t, k), vals("E2", t, k)
        if e1 and e2:
            aux.append(mean(e2) - mean(e1) > -NOISE[t])
    rows.append(("Auxiliary LM loss gives no gain on small datasets such as SST-2/MRPC",
                 verdict(all(aux), "reproduced", "not reproduced (it helped in our runs)", bool(aux))))
    z = load("E5_zeroshot_sst2.json")
    zok = bool(z) and 100 * z[0]["diagnostic_median_threshold"]["metrics"]["accuracy"] > 100 * z[0]["chance_majority_acc"] + 5
    rows.append(("The pre-trained LM carries task knowledge zero-shot",
                 verdict(zok, "reproduced (above chance)", "only weakly / not reproduced", bool(z))))
    return "| Paper's conclusion | Our result |\n|---|---|\n" + "\n".join(f"| {a} | {b} |" for a, b in rows)


# ----------------------------------------------------------------------------- assembly
def build(no_docx=False):
    with open(os.path.join(REP, "report_template.md"), encoding="utf-8") as f:
        text = f.read()
    V = values()
    text = re.sub(r"\{\{(\w+)\}\}", lambda m: V.get(m.group(1), f"{{{{{m.group(1)}}}}}"), text)

    def table(m):
        p = os.path.join(RES, "tables", m.group(1) + ".md")
        if os.path.exists(p):
            with open(p, encoding="utf-8") as f:
                return f.read().strip()
        return f"*Table `{m.group(1)}` not generated yet: run the experiments, then `python src/make_report_assets.py`.*"

    def fig(m):
        name, cap = m.group(1), m.group(2)
        if os.path.exists(os.path.join(RES, "figures", name)):
            return f"![{cap}](../results/figures/{name}){{width=100%}}"
        return f"*Figure `{name}` not generated yet ({cap}).*"

    text = re.sub(r"<!--TABLE:(\w+)-->", table, text)
    text = re.sub(r"<!--FIG:([\w.\-]+)\|(.*?)-->", fig, text)
    text = re.sub(r"<!--AUTO:(\w+)-->", lambda m: globals()[f"auto_{m.group(1)}"](), text)
    out_md = os.path.join(REP, "report.md")
    with open(out_md, "w", encoding="utf-8") as f:
        f.write(text)
    missing = text.count(NA) + text.count("not generated yet") + text.count("not done yet")
    print(f"wrote report/report.md ({len(text.split()):,} words; {missing} placeholders for runs not done)")
    if no_docx:
        return
    if not shutil.which("pandoc"):
        print("pandoc not found: install it to produce report.docx")
        return
    cmd = ["pandoc", "report.md", "-o", "report.docx", "--toc", "--resource-path=.:..",
           "--metadata", "link-citations=true"]
    ref = os.path.join(REP, "reference.docx")
    if os.path.exists(ref):
        cmd += ["--reference-doc", "reference.docx"]
    subprocess.run(cmd, cwd=REP, check=True)
    print("wrote report/report.docx")
    engine = next((e for e in ("xelatex", "lualatex", "pdflatex", "tectonic") if shutil.which(e)), None)
    if engine:
        r = subprocess.run(["pandoc", "report.md", "-o", "report.pdf", "--toc", f"--pdf-engine={engine}",
                            "--resource-path=.:..", "-V", "geometry:margin=2.2cm", "-V", "fontsize=11pt",
                            "-V", "mainfont=DejaVu Serif" if engine != "pdflatex" else "fontsize=11pt"],
                           cwd=REP)
        print("wrote report/report.pdf" if r.returncode == 0 else "PDF conversion failed (docx is still fine)")
    else:
        print("no LaTeX engine found: skipped report.pdf (open report.docx in Word and 'Save as PDF')")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-docx", action="store_true")
    build(ap.parse_args().no_docx)
